_target_: mnist.model.Model
encoder:
  _target_: mnist.model.Encoder
  input_dim: 784
  hidden_dim: 400
  latent_dim: 20
decoder:
  _target_: mnist.model.Decoder
  latent_dim: 20
  hidden_dim: 400
  output_dim: 784